import Foundation
import AppKit
import UniformTypeIdentifiers

/// Manages high-fidelity writing of screenshot image data to NSPasteboard.general.
/// Ensures maximum interoperability across macOS applications.
@MainActor
public final class ClipboardManager {
    public static let shared = ClipboardManager()

    private let pasteboard: NSPasteboard

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    /// Copies the given image and/or file URL to the system general pasteboard.
    /// Returns true if the pasteboard write succeeded.
    @discardableResult
    public func copy(
        image: NSImage,
        fileURL: URL? = nil,
        mode: ClipboardMode = AppSettings.shared.clipboardMode
    ) -> Bool {
        pasteboard.clearContents()

        let success: Bool
        switch mode {
        case .imageOnly:
            success = writeImageOnly(image: image, fileURL: fileURL, to: pasteboard)

        case .imageAndFile:
            success = writeImageAndFile(image: image, fileURL: fileURL, to: pasteboard)

        case .fileOnly:
            if let url = fileURL {
                success = writeFileOnly(url: url, to: pasteboard)
            } else {
                success = writeImageOnly(image: image, fileURL: fileURL, to: pasteboard)
            }
        }

        if success {
            AppLogger.shared.info("Successfully copied screenshot to clipboard (mode: \(mode.rawValue))")
        } else {
            AppLogger.shared.error("Failed to write screenshot to pasteboard")
        }

        return success
    }

    /// Copies text to clipboard (used by OCR feature).
    @discardableResult
    public func copyText(_ text: String) -> Bool {
        pasteboard.clearContents()
        return pasteboard.setString(text, forType: .string)
    }

    // MARK: - Private Pasteboard Writers

    @discardableResult
    private func writeImageOnly(image: NSImage, fileURL: URL? = nil, to pasteboard: NSPasteboard) -> Bool {
        var items: [NSPasteboardWriting] = []

        // 1. Prepare raw PNG representation (use direct file bytes if available for 0.1ms speed)
        var rawPNGData: Data?
        if let url = fileURL, url.pathExtension.lowercased() == "png", FileManager.default.fileExists(atPath: url.path) {
            rawPNGData = try? Data(contentsOf: url)
        }
        if rawPNGData == nil {
            rawPNGData = ImageUtils.pngData(from: image)
        }

        if let pngData = rawPNGData {
            let item = NSPasteboardItem()
            item.setData(pngData, forType: .png)
            item.setData(pngData, forType: NSPasteboard.PasteboardType("public.png"))

            // Also provide TIFF representation fallback
            if let tiffData = image.tiffRepresentation {
                item.setData(tiffData, forType: .tiff)
                item.setData(tiffData, forType: NSPasteboard.PasteboardType("public.tiff"))
            }

            addScreenshotMetadata(to: item, fileURL: fileURL)

            items.append(item)
        } else if let tiffData = image.tiffRepresentation {
            let item = NSPasteboardItem()
            item.setData(tiffData, forType: .tiff)
            addScreenshotMetadata(to: item, fileURL: fileURL)
            items.append(item)
        }

        if items.isEmpty {
            return pasteboard.writeObjects([image])
        } else {
            return pasteboard.writeObjects(items)
        }
    }

    @discardableResult
    private func writeImageAndFile(image: NSImage, fileURL: URL?, to pasteboard: NSPasteboard) -> Bool {
        let item = NSPasteboardItem()

        var rawPNGData: Data?
        if let url = fileURL, url.pathExtension.lowercased() == "png", FileManager.default.fileExists(atPath: url.path) {
            rawPNGData = try? Data(contentsOf: url)
        }
        if rawPNGData == nil {
            rawPNGData = ImageUtils.pngData(from: image)
        }

        if let pngData = rawPNGData {
            item.setData(pngData, forType: .png)
            item.setData(pngData, forType: NSPasteboard.PasteboardType("public.png"))
        }

        if let tiffData = image.tiffRepresentation {
            item.setData(tiffData, forType: .tiff)
        }

        addScreenshotMetadata(to: item, fileURL: fileURL)
        return pasteboard.writeObjects([item])
    }

    @discardableResult
    private func writeFileOnly(url: URL, to pasteboard: NSPasteboard) -> Bool {
        let item = NSPasteboardItem()
        addScreenshotMetadata(to: item, fileURL: url)
        return pasteboard.writeObjects([item])
    }

    private func addScreenshotMetadata(to item: NSPasteboardItem, fileURL: URL?) {
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        guard let fileURL else { return }
        item.setString(fileURL.absoluteString, forType: .fileURL)
        item.setString(shellQuoted(fileURL.path), forType: .string)
    }

    private func shellQuoted(_ path: String) -> String {
        "'" + path.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
