import AppKit
import Combine
import Foundation

public struct ClipboardHistoryItem: Identifiable, Equatable {
    public enum Kind: Equatable {
        case text
        case image
    }

    public let id = UUID()
    public let kind: Kind
    public let text: String?
    public let imageData: Data?
    public let imageType: NSPasteboard.PasteboardType?
    public let previewImage: NSImage?
    public let createdAt = Date()

    fileprivate let fingerprint: Int

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.id == rhs.id
    }
}

/// Keeps a small, in-memory history of ordinary clipboard text and images.
/// Password-manager and transient pasteboard entries are deliberately ignored.
@MainActor
public final class ClipboardHistoryManager: ObservableObject {
    public static let shared = ClipboardHistoryManager()

    @Published public private(set) var items: [ClipboardHistoryItem] = []
    @Published public private(set) var currentItem: ClipboardHistoryItem?

    private let pasteboard: NSPasteboard
    private var lastChangeCount: Int
    private var timer: Timer?

    private let maximumItems = 12
    private let maximumTextLength = 50_000
    private let maximumImageBytes = 8 * 1_024 * 1_024
    private let protectedTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    ]
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    public func startMonitoring() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.checkForChanges() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let availableTypes = Set(pasteboard.types ?? [])
        guard protectedTypes.allSatisfy({ !availableTypes.contains($0) }) else { return }

        if availableTypes.contains(autoGeneratedType) {
            currentItem = imageItemFromPasteboard()
            return
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           text.count <= maximumTextLength {
            let item = ClipboardHistoryItem(
                kind: .text,
                text: text,
                imageData: nil,
                imageType: nil,
                previewImage: nil,
                fingerprint: text.hashValue
            )
            currentItem = item
            add(item)
            return
        }

        if let item = imageItemFromPasteboard() {
            currentItem = item
            add(item)
        }
    }

    @discardableResult
    public func copy(_ item: ClipboardHistoryItem) -> Bool {
        pasteboard.clearContents()
        let copied: Bool
        switch item.kind {
        case .text:
            copied = item.text.map { pasteboard.setString($0, forType: .string) } ?? false
        case .image:
            guard let data = item.imageData, let type = item.imageType else { return false }
            let pasteboardItem = NSPasteboardItem()
            pasteboardItem.setData(data, forType: type)
            copied = pasteboard.writeObjects([pasteboardItem])
        }
        lastChangeCount = pasteboard.changeCount
        if copied { currentItem = item }
        return copied
    }

    public func clearHistory() {
        items.removeAll()
    }

    private func add(_ item: ClipboardHistoryItem) {
        guard items.first?.fingerprint != item.fingerprint else { return }
        items.insert(item, at: 0)
        if items.count > maximumItems {
            items.removeLast(items.count - maximumItems)
        }
    }

    private func imageItemFromPasteboard() -> ClipboardHistoryItem? {
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            guard let data = pasteboard.data(forType: type), data.count <= maximumImageBytes else { continue }
            return ClipboardHistoryItem(
                kind: .image,
                text: nil,
                imageData: data,
                imageType: type,
                previewImage: NSImage(data: data),
                fingerprint: data.hashValue
            )
        }
        return nil
    }
}
