import XCTest
import AppKit
@testable import ClipShotCore

@MainActor
final class ClipboardManagerTests: XCTestCase {

    func testImageClipboardCopy() {
        let size = NSSize(width: 100, height: 100)
        let image = NSImage(size: size)
        image.lockFocus()
        NSColor.red.drawSwatch(in: NSRect(origin: .zero, size: size))
        image.unlockFocus()

        let success = ClipboardManager.shared.copy(image: image, mode: .imageOnly)
        XCTAssertTrue(success)

        let pasteboard = NSPasteboard.general
        let types = pasteboard.types ?? []
        XCTAssertTrue(types.contains(.png) || types.contains(.tiff))
    }

    func testTextClipboardCopy() {
        let testText = "ClipShot OCR Extracted Text \(UUID().uuidString)"
        let success = ClipboardManager.shared.copyText(testText)
        XCTAssertTrue(success)

        let pasteboard = NSPasteboard.general
        let text = pasteboard.string(forType: .string)
        XCTAssertEqual(text, testText)
    }

    func testScreenshotCopyPastesAsTerminalPathWithoutEnteringClipboardHistory() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("clipshot-tests-\(UUID())"))
        let history = ClipboardHistoryManager(pasteboard: pasteboard)
        let manager = ClipboardManager(pasteboard: pasteboard)
        let size = NSSize(width: 10, height: 10)
        let image = NSImage(size: size)
        image.lockFocus()
        NSColor.blue.drawSwatch(in: NSRect(origin: .zero, size: size))
        image.unlockFocus()
        let fileURL = URL(fileURLWithPath: "/tmp/ClipShot user's screenshot.png")

        XCTAssertTrue(manager.copy(image: image, fileURL: fileURL, mode: .imageOnly))
        history.checkForChanges()

        XCTAssertEqual(
            pasteboard.string(forType: .string),
            "'/tmp/ClipShot user'\\''s screenshot.png'"
        )
        XCTAssertTrue(pasteboard.types?.contains(
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        ) == true)
        XCTAssertTrue(history.items.isEmpty)
        XCTAssertEqual(history.currentItem?.kind, .image)
    }
}
