import XCTest
import AppKit
@testable import ClipShotCore

@MainActor
final class ClipboardFormatTests: XCTestCase {

    private func shellQuoted(_ path: String) -> String {
        "'" + path.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    func testShellQuotingEscapesSpecialCharacters() {
        let normalPath = "/tmp/screenshot.png"
        XCTAssertEqual(shellQuoted(normalPath), "'/tmp/screenshot.png'")

        let spacesPath = "/Users/jane/My Screenshots/shot 1.png"
        XCTAssertEqual(shellQuoted(spacesPath), "'/Users/jane/My Screenshots/shot 1.png'")

        let quotesPath = "/tmp/John's Screenshot $2.png"
        XCTAssertEqual(shellQuoted(quotesPath), "'/tmp/John'\\''s Screenshot $2.png'")
    }

    func testFileOnlyClipboardMode() {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("clipshot-test-fileonly-\(UUID())"))
        let manager = ClipboardManager(pasteboard: pasteboard)
        let sampleURL = URL(fileURLWithPath: "/tmp/sample_clip.png")

        let success = manager.copy(image: NSImage(), fileURL: sampleURL, mode: .fileOnly)
        XCTAssertTrue(success)

        let stringContent = pasteboard.string(forType: .string)
        XCTAssertEqual(stringContent, "'/tmp/sample_clip.png'")

        let autoGen = pasteboard.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        XCTAssertEqual(autoGen, "1")
    }
}
