import XCTest
import AppKit
@testable import ClipShotCore

@MainActor
final class ClipboardFormatConcealmentTests: XCTestCase {

    private var customPasteboard: NSPasteboard!
    private var historyManager: ClipboardHistoryManager!

    override func setUp() async throws {
        try await super.setUp()
        let uniqueName = NSPasteboard.Name("org.clipshot.test.pasteboard.\(UUID().uuidString)")
        customPasteboard = NSPasteboard(name: uniqueName)
        historyManager = ClipboardHistoryManager(pasteboard: customPasteboard)
    }

    override func tearDown() async throws {
        customPasteboard.clearContents()
        customPasteboard = nil
        historyManager = nil
        try await super.tearDown()
    }

    func testConcealedTypePreventsHistoryIngestion() {
        customPasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString("SuperSecretPassword123!", forType: .string)
        // 1Password / macOS ConcealedType marker
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        customPasteboard.writeObjects([item])

        historyManager.checkForChanges()

        XCTAssertTrue(historyManager.items.isEmpty, "Concealed pasteboard item must not be recorded in clipboard history")
        XCTAssertNil(historyManager.currentItem)
    }

    func testTransientTypePreventsHistoryIngestion() {
        customPasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString("TemporaryTokenXYZ", forType: .string)
        // TransientType marker
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        customPasteboard.writeObjects([item])

        historyManager.checkForChanges()

        XCTAssertTrue(historyManager.items.isEmpty, "Transient pasteboard item must not be recorded in clipboard history")
        XCTAssertNil(historyManager.currentItem)
    }

    func testAutoGeneratedTypeUpdatesCurrentItemWithoutAddingToHistory() {
        customPasteboard.clearContents()
        let item = NSPasteboardItem()
        
        let rep = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: 2,
            pixelsHigh: 2,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 8,
            bitsPerPixel: 32
        )!
        let pngData = rep.representation(using: .png, properties: [:])!

        item.setData(pngData, forType: .png)
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        customPasteboard.writeObjects([item])

        historyManager.checkForChanges()

        XCTAssertTrue(historyManager.items.isEmpty, "AutoGeneratedType items should not be added to the history list")
        XCTAssertNotNil(historyManager.currentItem, "AutoGeneratedType should update currentItem for immediate reference")
    }

    func testRegularTextIsIngestedIntoHistory() {
        customPasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString("Hello, ClipShot history!", forType: .string)
        customPasteboard.writeObjects([item])

        historyManager.checkForChanges()

        XCTAssertEqual(historyManager.items.count, 1)
        XCTAssertEqual(historyManager.items.first?.text, "Hello, ClipShot history!")
        XCTAssertEqual(historyManager.currentItem?.text, "Hello, ClipShot history!")
    }

    func testOversizedTextExceedingLimitIsIgnored() {
        customPasteboard.clearContents()
        let oversizedText = String(repeating: "A", count: 50_001)
        let item = NSPasteboardItem()
        item.setString(oversizedText, forType: .string)
        customPasteboard.writeObjects([item])

        historyManager.checkForChanges()

        XCTAssertTrue(historyManager.items.isEmpty, "Text exceeding 50,000 characters should not be ingested into history")
    }
}
