#!/usr/bin/env swift
import Foundation
import AppKit

print("--- ClipShot: Multi-Flavor NSPasteboard Item Inspector ---")

// Create an isolated pasteboard instance for demonstration
let testPasteboardName = NSPasteboard.Name("org.clipshot.examples.pasteboard.\(UUID().uuidString)")
let pasteboard = NSPasteboard(name: testPasteboardName)

print("1. Preparing Multi-Flavor Screenshot Pasteboard Item...")

// Create a synthetic 4x4 image
let rep = NSBitmapImageRep(
    bitmapDataPlanes: nil,
    pixelsWide: 4,
    pixelsHigh: 4,
    bitsPerSample: 8,
    samplesPerPixel: 4,
    hasAlpha: true,
    isPlanar: false,
    colorSpaceName: .deviceRGB,
    bytesPerRow: 16,
    bitsPerPixel: 32
)!

let pngData = rep.representation(using: .png, properties: [:])!
let tiffData = rep.representation(using: .tiff, properties: [:])!
let fileURL = URL(fileURLWithPath: "/Users/test/Desktop/Screen Shot 2026-09-29.png")

let item = NSPasteboardItem()

// Flavor 1: PNG format (Primary image flavor for messaging apps & web)
item.setData(pngData, forType: NSPasteboard.PasteboardType("public.png"))

// Flavor 2: TIFF format (Legacy Apple system flavor for Cocoa apps)
item.setData(tiffData, forType: NSPasteboard.PasteboardType("public.tiff"))

// Flavor 3: File URL (Finder / drag-and-drop representation)
item.setString(fileURL.absoluteString, forType: NSPasteboard.PasteboardType("public.file-url"))

// Flavor 4: AutoGenerated marker (Tells clipboard managers not to loop on this screenshot)
item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))

pasteboard.clearContents()
let writeSuccess = pasteboard.writeObjects([item])

print("   Write Success: \(writeSuccess ? "YES ✅" : "NO ❌")")
print("   Change Count: \(pasteboard.changeCount)\n")

print("2. Querying Pasteboard Flavors (Types) Registered:")
if let types = pasteboard.types {
    for (i, type) in types.enumerated() {
        let raw = type.rawValue
        var description = "Standard Flavor"
        if raw.contains("png") { description = "Web & Chat Compressed Bitmap" }
        else if raw.contains("tiff") { description = "High-Fidelity Uncompressed Bitmap" }
        else if raw.contains("file-url") { description = "Filesystem Reference" }
        else if raw.contains("AutoGenerated") { description = "ClipShot Attribution Marker" }

        print("  [\(i + 1)] \(raw) (\(description))")
    }
}

print("\n3. Testing Flavor Extraction by Target Consumer:")
// A web browser asking for PNG:
if let extractedPNG = pasteboard.data(forType: NSPasteboard.PasteboardType("public.png")) {
    print("  • Web/Chat Client extracted PNG: \(extractedPNG.count) bytes ✅")
}

// Finder asking for File URL:
if let extractedURL = pasteboard.string(forType: NSPasteboard.PasteboardType("public.file-url")) {
    print("  • Finder extracted URL: \(extractedURL) ✅")
}

// Clipboard manager checking for loop prevention:
if pasteboard.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) != nil {
    print("  • Clipboard Manager: Detected AutoGeneratedType - skipping duplicate notification ✅")
}
