#!/usr/bin/env swift
import Foundation
import AppKit

print("--- ClipShot: NSPasteboard Type Inspector & Security Filter ---")

struct PasteboardDescriptor {
    let identifier: String
    let description: String
    let isProtected: Bool
}

let monitoredTypes: [PasteboardDescriptor] = [
    PasteboardDescriptor(identifier: "public.png", description: "Portable Network Graphics image", isProtected: false),
    PasteboardDescriptor(identifier: "public.tiff", description: "Tagged Image File Format", isProtected: false),
    PasteboardDescriptor(identifier: "public.utf8-plain-text", description: "Plain UTF-8 text string", isProtected: false),
    PasteboardDescriptor(identifier: "public.file-url", description: "File path reference URL", isProtected: false),
    PasteboardDescriptor(identifier: "org.nspasteboard.ConcealedType", description: "Password manager secret (ignored for privacy)", isProtected: true),
    PasteboardDescriptor(identifier: "org.nspasteboard.TransientType", description: "Temporary item without persistence history", isProtected: true),
    PasteboardDescriptor(identifier: "org.nspasteboard.AutoGeneratedType", description: "System auto-generated clipboard content", isProtected: false)
]

func evaluatePasteboardPayload(types: [String]) -> (shouldRecord: Bool, reason: String) {
    let typeSet = Set(types)
    let protected = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType"]

    if let hit = protected.first(where: { typeSet.contains($0) }) {
        return (false, "Rejected: contains protected privacy flag [\(hit)]")
    }

    if typeSet.contains("public.png") || typeSet.contains("public.tiff") {
        return (true, "Accepted: valid image payload detected")
    }

    if typeSet.contains("public.utf8-plain-text") {
        return (true, "Accepted: valid plain text payload detected")
    }

    return (false, "Ignored: unsupported or unrecognized payload types")
}

let testCases: [(name: String, types: [String])] = [
    ("Standard Screenshot Copy", ["public.png", "public.tiff", "public.file-url"]),
    ("1Password Password Copy", ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]),
    ("Raycast Transient Snippet", ["public.utf8-plain-text", "org.nspasteboard.TransientType"]),
    ("Notes App Rich Text", ["public.utf8-plain-text", "public.rtf"]),
    ("Audio / Binary Blob", ["com.apple.sound", "public.data"])
]

for test in testCases {
    let (shouldRecord, reason) = evaluatePasteboardPayload(types: test.types)
    print("Scenario: [\(test.name)]")
    print("  Available Types: \(test.types.joined(separator: ", "))")
    print("  Decision: [\(shouldRecord ? "CAPTURE" : "DISCARD")] -> \(reason)\n")
}
